# Generated by Django 5.2.13 on 2026-04-21 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=60, unique=True)),
                (
                    "currency",
                    models.CharField(
                        choices=[("UAH", "₴ Гривня"), ("USD", "$ Долар"), ("EUR", "€ Євро")],
                        default="UAH",
                        max_length=3,
                    ),
                ),
                (
                    "default_language",
                    models.CharField(
                        choices=[
                            ("uk", "Українська"),
                            ("en", "English"),
                            ("pl", "Polski"),
                            ("de", "Deutsch"),
                            ("fr", "Français"),
                            ("es", "Español"),
                            ("it", "Italiano"),
                            ("ru", "Русский"),
                        ],
                        default="uk",
                        help_text="Мова, якою створюються назви/описи товарів у основних полях.",
                        max_length=5,
                    ),
                ),
                (
                    "languages",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Коди додаткових мов, на які магазин перекладає товари.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_shops",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ShopMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Власник"),
                            ("admin", "Адмін"),
                            ("staff", "Співробітник"),
                            ("viewer", "Переглядач"),
                        ],
                        default="staff",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="shops.shop",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "unique_together": {("shop", "user")},
            },
        ),
    ]
