# Generated by Django 5.2.13 on 2026-04-21 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("shops", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("receipt", "Прихід"),
                            ("issue", "Видача"),
                            ("adjustment", "Корекція"),
                            ("writeoff", "Списання"),
                        ],
                        default="receipt",
                        max_length=12,
                    ),
                ),
                (
                    "delta",
                    models.IntegerField(
                        help_text="Зміна залишку: додатне для приходу, відʼємне для видачі."
                    ),
                ),
                (
                    "balance_after",
                    models.IntegerField(help_text="Залишок товару після застосування руху."),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_movements",
                        to="catalog.product",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="shops.shop",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["shop", "-created_at"], name="inventory_s_shop_id_a8eaf5_idx"
                    ),
                    models.Index(fields=["product"], name="inventory_s_product_cbdc37_idx"),
                ],
            },
        ),
    ]
