# Generated by Django 5.2.13 on 2026-04-21 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sku", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("stock", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "translations",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Формат: {"en": {"name": "...", "description": "..."}, "pl": {...}}',
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="shops.shop",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["shop", "is_active"], name="catalog_pro_shop_id_1d6557_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("shop", "sku"), name="catalog_unique_sku_per_shop"
                    )
                ],
            },
        ),
    ]
