# Generated by Django 5.2.13 on 2026-04-21 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("sku", models.CharField(max_length=48)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("stock", models.PositiveIntegerField(default=0)),
                ("position", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ("position", "id"),
            },
        ),
        migrations.AddField(
            model_name="product",
            name="barcode",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("coffee", "Кава та чай"),
                    ("clothes", "Одяг"),
                    ("cosmetics", "Косметика"),
                    ("handmade", "Хендмейд"),
                    ("food", "Продукти"),
                    ("other", "Інше"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="channels",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="product",
            name="compare_at_price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="cost",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="meta_description",
            field=models.TextField(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name="product",
            name="meta_title",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="product",
            name="producer",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Список рядків-тегів (для пошуку, фільтрів, аналітики).",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="url_slug",
            field=models.SlugField(
                blank=True,
                help_text="Суфікс URL товару на публічній вітрині (унікальний у межах магазину).",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="vat_status",
            field=models.CharField(
                choices=[("none", "Без ПДВ"), ("20", "ПДВ 20%"), ("7", "ПДВ 7%")],
                default="none",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="weight_grams",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["shop", "category"], name="catalog_pro_shop_id_e6a2bb_idx"),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                condition=models.Q(("url_slug", ""), _negated=True),
                fields=("shop", "url_slug"),
                name="catalog_unique_url_slug_per_shop",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variants",
                to="catalog.product",
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.UniqueConstraint(
                fields=("product", "sku"), name="catalog_unique_variant_sku_per_product"
            ),
        ),
    ]
