# Generated by Django 5.2.13 on 2026-04-21 12:34

import apps.catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_productvariant_product_barcode_product_brand_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("image", models.FileField(upload_to=apps.catalog.models._product_image_path)),
                (
                    "position",
                    models.IntegerField(default=0, help_text="Порядок у списку зображень."),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Головне зображення — використовується як hero на картці товару.",
                    ),
                ),
                (
                    "alt",
                    models.CharField(
                        blank=True, help_text="Alt-текст для SEO/доступності.", max_length=200
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ("position", "id"),
            },
        ),
    ]
