# Generated by Django 5.2.13 on 2026-04-21 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("shops", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Thread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("web", "Web"),
                            ("ig", "Instagram"),
                            ("tg", "Telegram"),
                            ("viber", "Viber"),
                            ("manual", "Manual"),
                        ],
                        default="web",
                        max_length=8,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=200)),
                (
                    "external_id",
                    models.CharField(
                        blank=True, help_text="ID у зовнішньому месенджері.", max_length=120
                    ),
                ),
                ("unread", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inbox_threads",
                        to="customers.customer",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inbox_threads",
                        to="shops.shop",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at",),
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("in", "Inbound"), ("out", "Outbound")], max_length=3
                    ),
                ),
                ("author_name", models.CharField(blank=True, max_length=120)),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="inbox.thread",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="thread",
            index=models.Index(
                fields=["shop", "-updated_at"], name="inbox_threa_shop_id_fb2444_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="thread",
            index=models.Index(fields=["shop", "channel"], name="inbox_threa_shop_id_10d243_idx"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["thread", "created_at"], name="inbox_messa_thread__ffefba_idx"
            ),
        ),
    ]
